version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: root
  BeforeInstall:
    - location: privileges.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: root
 