version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - apt-get update    
      - sudo apt install -y mysql-client  

  pre_build:
    commands:
      # - echo connection to database 
      # - echo spring.datasource.username="user"
      # - echo spring.datasource.password="0eg)Q5<-sT]bPR}O5dZ!Km|!*cY+"
      # - echo spring.datasource.url="jdbc:mysql://java-dbs.cmuokqciitb8.us-east-1.rds.amazonaws.com:3306/book?ServerTimezone=UTC"

      - echo spring.datasource.username=$(aws secretsmanager get-secret-value --secret-id $SECRETS_ID --query SecretString  | jq -r '. | fromjson | .username') >> src/main/resources/application.properties
      - pass=$(aws secretsmanager get-secret-value --secret-id $SECRETS_ID --query SecretString  | jq -r '. | fromjson | .password')
      - echo spring.datasource.password=$pass >> src/main/resources/application.properties
      - echo spring.datasource.url=jdbc:mysql://$RDS_HOSTNAME:$RDS_PORT/$RDS_DB_NAME?ServerTimezone=UTC >> src/main/resources/application.properties
      - sudo mysql -h $RDS_HOSTNAME -P 3306 -u root -p$pass
      
  build:
    commands:
      - echo Compiling the application...
      - mvn clean package
     
  post_build:
    commands:
      - mvn test
      - echo Packaging artifacts...

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes